# Generated by Django 3.1.6 on 2021-02-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth', models.IntegerField()),
                ('death', models.IntegerField()),
                ('works', models.TextField(max_length=250)),
                ('quote', models.TextField(max_length=500)),
            ],
        ),
    ]
