# Generated by Django 3.1.6 on 2021-02-04 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='quote',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='writer',
            name='works',
            field=models.TextField(max_length=500),
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dawn', models.TextField(max_length=1000)),
                ('sunrise', models.TextField(max_length=1000)),
                ('morning', models.TextField(max_length=1000)),
                ('noon', models.TextField(max_length=1000)),
                ('afternoon', models.TextField(max_length=1000)),
                ('evening', models.TextField(max_length=1000)),
                ('sunset', models.TextField(max_length=1000)),
                ('dusk', models.TextField(max_length=1000)),
                ('night', models.TextField(max_length=1000)),
                ('midnight', models.TextField(max_length=1000)),
                ('source', models.TextField(max_length=1000)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.writer')),
            ],
        ),
    ]
