# Generated by Django 3.1.6 on 2021-02-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210204_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='writer',
        ),
    ]
