# Generated by Django 3.1.6 on 2021-02-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_routine_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='title',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
