# Generated by Django 3.1.6 on 2021-02-04 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_remove_routine_writer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routine',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='routine',
            name='title',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routine',
            name='writer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.writer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
