# Generated by Django 3.1.6 on 2021-02-04 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210204_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='user',
        ),
    ]
