# Generated by Django 3.1.6 on 2021-02-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_writer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='dawn',
            field=models.TextField(blank=True),
        ),
    ]
