# Generated by Django 3.1.6 on 2021-02-04 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210204_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='writer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.writer'),
            preserve_default=False,
        ),
    ]
