# Generated by Django 3.1.6 on 2021-02-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210206_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='afternoon',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='dusk',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='evening',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='midnight',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='morning',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='night',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='noon',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='source',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='sunrise',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='sunset',
            field=models.TextField(blank=True),
        ),
    ]
