# Generated by Django 3.1.6 on 2021-02-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210206_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writer',
            options={'ordering': ['name']},
        ),
    ]
